---
apiVersion: v1
kind: ReplicationController
metadata:
  name: teamspeak-controller
  labels:
    heritage: helm
spec:
  replicas: ${REPLICAS}
  selector:
    app: teamspeak
  template:
    metadata:
      labels:
        heritage: helm
        app: teamspeak
    spec:
      containers:
      - name: teamspeak
        image: "asos/teamspeak:2.1.1.1"
        ports:
            - "${HOST_VOICE_PORT}:9987/udp"
            - "${HOST_QUERY_PORT}:10011"
            - "${HOST_FILE_TRANSFER_PORT}:30033"
        env:
            - TS3_MARIADB_HOST=${TS3_MARIADB_HOST}
            - TS3_MADIADB_PORT=${TS3_MARIADB_PORT}
            - TS3_MARIDDB_USER=${TS3_MARIADB_USER}
            - TS3_MARIDDB_PASS=${TS3_MARIADB_PASS}
            - TS3_MARIDDB_DB=${TS3_MARIADB_DB}
            - TS3_LICENSE_PATH=${TS3_MARIADB_LICENSE_PATH}
        volumeMounts:
          - mountPath: /storage/teamspeak
            name: teamspeak-data
      volumes:
        - name: teamspeak-data
          emptyDir: {}
