name: ASoS Let's Encrypt
description: |
  Trusted SSL certificates at zero cost
version: 0.0.1
category: Certificates
maintainer: ASoS Gaming Community(asosdevelopment@asosgaming.software)
support: [Report an Issue](https://github.com/asosgaming/asos-letsencrypt/issues)
