apiVersion: v1
kind: Service
metadata:
  name: rust
  labels:
    heritage: helm
spec:
  type: LoadBalancer
  ports:
  - port: ${LB_PORT}
    targetPort: 25565
    protocol: TCP
  selector:
    app: rust
